### ISSUE TITLE
Package Name?

### ISSUE THREAD

**Issue by sarahsturgeon** [JamieGrimwood/wisp.js#1]
Hi there, I see that this package isn't currently used.

I'm releasing a heft API package that I'm calling "WispJS" (a package that interacts with "Wisp" Game Panels).

If you're not currently using it, would you be okay giving it up?

ref: https://www.npmjs.com/package/wisp.js

**Comment by JamieGrimwood** [comment]
Hey,

I'm really sorry I didn't get back to you sooner! Yes, you can have it. That was the original plan for this package but I sadly never had the time, glad someone could make it into something I couldn't. Contact me on discord and we'll get it sorted! jameigrimwood

**Comment by sarahsturgeon** [comment]
Hi there,

Thanks for the reply! I'd love to show you what I came up with.

I couldn't add the given username on discord, you can try adding me: `phatso`
